import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { DskImage } from '@/app/store/dsk-workspace/dsk-workspace'
import { generateDskFilenames } from '@/components/dsk-workspace/dsk-workspace-utils'

/**
 * Generate PDF README for DSK export
 * Converts markdown content to formatted PDF
 */
export function generateDskReadmePdf(
  images: DskImage[],
  dskFilename: string
): Blob {
  const doc = new jsPDF()
  let yPosition = 20

  // Title
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text(dskFilename, 20, yPosition)
  yPosition += 10

  // Generation date
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
  doc.text(`Generated by Pixsaur on ${date}`, 20, yPosition)
  yPosition += 15

  // Contents section
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('Contents', 20, yPosition)
  yPosition += 8

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(
    `This DSK contains ${images.length} image(s) converted for Amstrad CPC.`,
    20,
    yPosition
  )
  yPosition += 10

  // Files table
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Files', 20, yPosition)
  yPosition += 5

  const filesTableData: string[][] = []
  for (let i = 0; i < images.length; i++) {
    const image = images[i]
    const imageIndex = i + 1
    const filenames = generateDskFilenames(
      imageIndex,
      image.width,
      image.height,
      image.mode,
      image.overscan
    )
    const hardware = image.cpcHardware === 'plus' ? 'CPC Plus' : 'CPC Classic'
    const mode = `Mode ${image.mode}`
    const dimensions = `${image.width}×${image.height}`
    const colors = String(image.nColors)
    const rasters =
      image.rasterRanges && image.rasterRanges.length > 0
        ? `${image.rasterRanges.length} range(s)`
        : '-'

    if (filenames.length === 1) {
      filesTableData.push([
        filenames[0],
        hardware,
        mode,
        dimensions,
        colors,
        rasters
      ])
    } else {
      filesTableData.push([
        `${filenames[0].replace(/_1\.BIN$/, '.BIN')} (${filenames.length} chunks)`,
        hardware,
        mode,
        dimensions,
        colors,
        rasters
      ])
    }
  }

  autoTable(doc, {
    startY: yPosition,
    head: [['Filename', 'Hardware', 'Mode', 'Dimensions', 'Colors', 'Rasters']],
    body: filesTableData,
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185] },
    styles: { fontSize: 9 }
  })

  yPosition = (doc as any).lastAutoTable.finalY + 10

  // Check if any images have rasters
  const hasRasters = images.some(
    (img) => img.rasterRanges && img.rasterRanges.length > 0
  )

  if (hasRasters) {
    if (yPosition > 230) {
      doc.addPage()
      yPosition = 20
    }

    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text('Raster Data', 20, yPosition)
    yPosition += 8

    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    const rasterIntro =
      'Some images include raster data (rasterX.asm files). Rasters allow changing ink colors per scanline for advanced visual effects.'
    const splitRasterIntro = doc.splitTextToSize(rasterIntro, 170)
    doc.text(splitRasterIntro, 20, yPosition)
    yPosition += 6 * splitRasterIntro.length + 4

    doc.setFont('helvetica', 'bold')
    doc.text('Format:', 20, yPosition)
    yPosition += 6

    doc.setFont('helvetica', 'normal')
    doc.text('CPC Classic: DB ink, color (2 bytes per line)', 25, yPosition)
    yPosition += 5
    doc.text(
      'CPC Plus: DB ink, color_low, color_high (3 bytes per line)',
      25,
      yPosition
    )
    yPosition += 5
    doc.text(
      '#FF, #FF (or #FF, #FF, #FF) = no change on this line',
      25,
      yPosition
    )
    yPosition += 8

    const rasterNote =
      'The raster data includes automatic restoration of original palette colors when a raster range ends.'
    const splitRasterNote = doc.splitTextToSize(rasterNote, 170)
    doc.text(splitRasterNote, 20, yPosition)
    yPosition += 6 * splitRasterNote.length + 8
  }

  if (yPosition > 250) {
    doc.addPage()
    yPosition = 20
  }

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('How to use', 20, yPosition)
  yPosition += 8

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Standard SCR files (from BASIC):', 20, yPosition)
  yPosition += 6

  doc.setFont('courier', 'normal')
  doc.setFontSize(9)
  doc.text('MEMORY &7FFF', 25, yPosition)
  yPosition += 5
  doc.text('LOAD"LOADER.BIN",&8000', 25, yPosition)
  yPosition += 5
  doc.text('A$="IMG1.SCR"', 25, yPosition)
  yPosition += 5
  doc.text('CALL &8000, @A$', 25, yPosition)
  yPosition += 8

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  const loaderText =
    'The loader automatically detects CPC Classic or CPC Plus format and applies the appropriate palette. This only works for standard .SCR files.'
  const splitText = doc.splitTextToSize(loaderText, 170)
  doc.text(splitText, 20, yPosition)
  yPosition += 6 * splitText.length + 8

  // Footer
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.text(
      'Generated with Pixsaur (https://pixsaur.iiivan.org/) - Image converter for Amstrad CPC',
      20,
      285
    )
    doc.setFont('helvetica', 'normal')
    doc.text(`Page ${i} of ${totalPages}`, 180, 285)
  }

  return doc.output('blob')
}
