import { describe, expect, it } from 'vitest'
import { generateDskReadme } from './generate-dsk-readme'
import type { DskImage } from './types'

function makeImage(overrides: Partial<DskImage> = {}): DskImage {
  return {
    id: 'img-1',
    name: 'image',
    scrData: [],
    mode: 1,
    width: 320,
    height: 200,
    overscan: false,
    nColors: 16,
    scaleX: 1,
    scaleY: 1,
    cpcHardware: 'classic',
    paletteFirmware: [],
    ...overrides
  }
}

describe('generateDskReadme', () => {
  describe('header and intro', () => {
    it('uses the DSK filename as the top-level heading', () => {
      const readme = generateDskReadme([], 'my-disk.dsk')
      expect(readme.startsWith('# my-disk.dsk\n\n')).toBe(true)
    })

    it('includes a Pixsaur generation credit line', () => {
      const readme = generateDskReadme([], 'demo.dsk')
      expect(readme).toContain('Generated by Pixsaur on ')
    })

    it('reports the number of images as 0 for an empty DSK', () => {
      const readme = generateDskReadme([], 'empty.dsk')
      expect(readme).toContain(
        'This DSK contains 0 image(s) converted for Amstrad CPC.'
      )
    })

    it('reports the correct image count for a multi-file DSK', () => {
      const images = [makeImage(), makeImage(), makeImage()]
      const readme = generateDskReadme(images, 'multi.dsk')
      expect(readme).toContain(
        'This DSK contains 3 image(s) converted for Amstrad CPC.'
      )
    })
  })

  describe('files table', () => {
    it('renders the files table header and separator', () => {
      const readme = generateDskReadme([], 'x.dsk')
      expect(readme).toContain(
        '| Filename | Hardware | Mode | Dimensions | Colors |'
      )
      expect(readme).toContain(
        '|----------|----------|------|------------|--------|'
      )
    })

    it('lists a standard CPC Classic Mode 1 image as a .SCR row', () => {
      const images = [
        makeImage({
          mode: 1,
          width: 320,
          height: 200,
          overscan: false,
          nColors: 16,
          cpcHardware: 'classic'
        })
      ]
      const readme = generateDskReadme(images, 'x.dsk')
      expect(readme).toContain(
        '| IMG1.SCR | CPC Classic | Mode 1 | 320×200 | 16 |'
      )
    })

    it('labels CPC Plus hardware in the row', () => {
      const images = [
        makeImage({
          mode: 0,
          width: 160,
          height: 200,
          nColors: 16,
          cpcHardware: 'plus',
          paletteFirmware: [],
          palettePlus: [0x123]
        })
      ]
      const readme = generateDskReadme(images, 'x.dsk')
      expect(readme).toContain(
        '| IMG1.SCR | CPC Plus | Mode 0 | 160×200 | 16 |'
      )
    })

    it('uses .BIN filenames for custom (overscan) dimensions', () => {
      const images = [
        makeImage({
          mode: 1,
          width: 320,
          height: 200,
          overscan: true
        })
      ]
      const readme = generateDskReadme(images, 'x.dsk')
      expect(readme).toContain('| IMG1.BIN |')
    })

    it('numbers rows with a 1-based index across multiple images', () => {
      const images = [
        makeImage({ id: 'a' }),
        makeImage({ id: 'b' }),
        makeImage({ id: 'c' })
      ]
      const readme = generateDskReadme(images, 'x.dsk')
      expect(readme).toContain('| IMG1.SCR |')
      expect(readme).toContain('| IMG2.SCR |')
      expect(readme).toContain('| IMG3.SCR |')
      expect(readme).not.toContain('| IMG4.SCR |')
    })
  })

  describe('static documentation sections', () => {
    it('includes the BASIC usage instructions', () => {
      const readme = generateDskReadme([], 'x.dsk')
      expect(readme).toContain('### How to use')
      expect(readme).toContain('MEMORY &7FFF')
      expect(readme).toContain('LOAD"LOADER.BIN",&8000')
      expect(readme).toContain('CALL &8000, @A$')
    })

    it('documents the SCR file format and memory layout', () => {
      const readme = generateDskReadme([], 'x.dsk')
      expect(readme).toContain('## SCR File Format')
      expect(readme).toContain(
        'Each .SCR file is 16KB (16384 bytes) with embedded metadata'
      )
      expect(readme).toContain(
        '### Memory Layout (offsets relative to file start)'
      )
      expect(readme).toContain(
        '| 0x0000-0x3FFF | 16384 | Screen data (pixel data in CPC format) |'
      )
    })

    it('documents both Classic and Plus metadata formats', () => {
      const readme = generateDskReadme([], 'x.dsk')
      expect(readme).toContain('#### CPC Classic Format')
      expect(readme).toContain('| 2035 | 1 | Hardware type (0 = Classic) |')
      expect(readme).toContain('#### CPC Plus Format')
      expect(readme).toContain('| 2035 | 1 | Hardware type (1 = Plus) |')
      expect(readme).toContain('0000 GGGG RRRR BBBB')
    })

    it('ends with the Pixsaur footer link', () => {
      const readme = generateDskReadme([], 'x.dsk')
      expect(readme).toContain(
        'Generated with [Pixsaur](https://pixsaur.iiivan.org/) - Image converter for Amstrad CPC'
      )
      expect(readme.trimEnd().endsWith('for Amstrad CPC')).toBe(true)
    })
  })

  describe('palette information section', () => {
    it('always renders the Palette Information heading', () => {
      const readme = generateDskReadme([], 'x.dsk')
      expect(readme).toContain('### Palette Information')
    })

    it('prints firmware indices for a CPC Classic image', () => {
      const images = [
        makeImage({
          cpcHardware: 'classic',
          paletteFirmware: [1, 24, 20, 6]
        })
      ]
      const readme = generateDskReadme(images, 'x.dsk')
      expect(readme).toContain('**IMG1.SCR** (CPC Classic)')
      expect(readme).toContain('Firmware indices:')
      expect(readme).toContain('[1, 24, 20, 6]')
    })

    it('prints hex GRB hardware values for a CPC Plus image', () => {
      const images = [
        makeImage({
          cpcHardware: 'plus',
          paletteFirmware: [],
          palettePlus: [0x123, 0xf, 0xabc]
        })
      ]
      const readme = generateDskReadme(images, 'x.dsk')
      expect(readme).toContain('**IMG1.SCR** (CPC Plus)')
      expect(readme).toContain('Hardware values (GRB format):')
      // 0xf is zero-padded to 3 hex digits and uppercased
      expect(readme).toContain('[#123, #00F, #ABC]')
    })

    it('omits the firmware block when a Classic palette is empty', () => {
      const images = [
        makeImage({ cpcHardware: 'classic', paletteFirmware: [] })
      ]
      const readme = generateDskReadme(images, 'x.dsk')
      expect(readme).toContain('**IMG1.SCR** (CPC Classic)')
      expect(readme).not.toContain('Firmware indices:')
    })

    it('omits the hardware block when a Plus palette is missing', () => {
      const images = [
        makeImage({
          cpcHardware: 'plus',
          paletteFirmware: [],
          palettePlus: undefined
        })
      ]
      const readme = generateDskReadme(images, 'x.dsk')
      expect(readme).toContain('**IMG1.SCR** (CPC Plus)')
      expect(readme).not.toContain('Hardware values (GRB format):')
    })

    it('renders a per-image palette entry for each image', () => {
      const images = [
        makeImage({ cpcHardware: 'classic', paletteFirmware: [1, 2] }),
        makeImage({
          cpcHardware: 'plus',
          paletteFirmware: [],
          palettePlus: [0x456]
        })
      ]
      const readme = generateDskReadme(images, 'x.dsk')
      expect(readme).toContain('**IMG1.SCR** (CPC Classic)')
      expect(readme).toContain('[1, 2]')
      expect(readme).toContain('**IMG2.SCR** (CPC Plus)')
      expect(readme).toContain('[#456]')
    })
  })

  describe('determinism', () => {
    it('produces identical output for identical input', () => {
      const images = [
        makeImage({ cpcHardware: 'classic', paletteFirmware: [1] })
      ]
      const a = generateDskReadme(images, 'same.dsk')
      const b = generateDskReadme(images, 'same.dsk')
      expect(a).toBe(b)
    })
  })
})
