import { atom } from 'jotai'
import { logger } from '@/core'
import type { Vector } from '@/libs/pixsaur-color/src/type'
import {
  applyDitheringWithRaster,
  createRasterPreviewImageData,
  MODE_0_FIXED_COLORS,
  MODE_0_TOTAL_COLORS,
  optimizeLinePalettesWithIndexBuffer,
  preprocessImageForRaster
} from '@/libs/pixsaur-raster'
import type { RasterChange } from '@/libs/pixsaur-raster/types'
import { cpcPalette } from '@/palettes/cpc-palette'
import { imageProcessorAtom } from '../adapters/processors'
import {
  configAtom,
  cpcHardwareAtom,
  ditheringAtom,
  effectiveModeConfigAtom,
  egxEnabledAtom,
  modeREnabledAtom,
  paletteStrategyAtom
} from '../config/config'
import { imageAtom, selectionAtom } from '../image/image'
import {
  finalEgxIndexBufferAtom,
  finalEgxPreviewImageAtom
} from '../preview/egx-preview'
import { modeRPreviewImageAtom } from '../preview/mode-r-preview'
import {
  applyManualEditsToBuffer,
  exportPaletteWithSlotsAtom,
  finalPreviewImageAtom,
  finalPreviewIndexBufferAtom,
  hasManualEditsAtom,
  manualPixelEditsAtom,
  positionedNormalizedImageAtom,
  previewImageAtom
} from '../preview/preview'
import {
  rasterChangesAtom,
  rasterDitheringIntensityAtom,
  rasterEnabledAtom,
  rasterMaxChangesPerLineAtom
} from './raster-config'

// Re-export primitive atoms for external use
export {
  rasterChangesAtom,
  rasterDitheringIntensityAtom,
  rasterEnabledAtom,
  rasterMaxChangesPerLineAtom
} from './raster-config'

/**
 * Version counter that increments each time raster optimization completes.
 * Used to force re-evaluation of preview atoms even if data dimensions are the same.
 */
export const rasterVersionAtom = atom(0)

/**
 * Raw optimization result from the raster algorithm (without final dithering).
 * This is generated by the optimization algorithm and stores:
 * - optimizedIndexBuffer: pixel indices based on raster changes (no final dithering)
 * - quantizedGlobalPalette: the base palette before any raster changes
 * - rasterChanges: the array of raster changes (without IDs)
 * - preprocessedImage: the source image used for optimization (for dithering)
 * - dimensions: width and height
 */
export const rasterOptimizationResultAtom = atom<{
  optimizedIndexBuffer: Uint8Array
  quantizedGlobalPalette: Vector<'RGB'>[]
  rasterChanges: Array<Omit<RasterChange, 'id'>>
  preprocessedImage: ImageData
  width: number
  height: number
} | null>(null)

/**
 * Optimized index buffer for raster rendering with final dithering applied.
 * This is a derived atom that:
 * 1. Takes the raw optimization result (without final dithering)
 * 2. Applies the user-configured final dithering respecting per-line palettes
 * 3. Returns the final index buffer ready for rendering
 *
 * Automatically recalculates when dithering config changes.
 */
export const rasterIndexBufferAtom = atom((get) => {
  const result = get(rasterOptimizationResultAtom)
  if (!result) return null

  const ditheringConfig = get(ditheringAtom)
  const modeConfig = get(effectiveModeConfigAtom)

  const {
    optimizedIndexBuffer,
    quantizedGlobalPalette,
    rasterChanges,
    preprocessedImage,
    width,
    height
  } = result

  // If no dithering configured, return the optimized buffer as-is
  if (ditheringConfig.mode === 'none' || ditheringConfig.intensity === 0) {
    return {
      buffer: optimizedIndexBuffer,
      width,
      height,
      palette: quantizedGlobalPalette
    }
  }

  // Apply final dithering with per-line palettes
  const finalIndexBuffer = applyDitheringWithRaster(
    preprocessedImage,
    quantizedGlobalPalette,
    rasterChanges,
    ditheringConfig,
    modeConfig.nColors
  )

  return {
    buffer: finalIndexBuffer,
    width,
    height,
    palette: quantizedGlobalPalette
  }
})

/**
 * Final raster index buffer with manual pixel edits applied.
 * Applies manual edits on top of the raster-optimized buffer.
 */
export const finalRasterIndexBufferAtom = atom((get) => {
  const rasterBuffer = get(rasterIndexBufferAtom)
  if (!rasterBuffer) return null

  const edits = get(manualPixelEditsAtom)
  return applyManualEditsToBuffer(rasterBuffer, edits)
})

/**
 * Effective index buffer for editing: returns the appropriate buffer based on
 * the active mode:
 * - EGX mode: returns the EGX index buffer
 * - Raster mode: returns the raster-optimized buffer
 * - Standard: returns the standard preview buffer
 * This is the buffer that should be used when entering the editor.
 */
export const effectiveIndexBufferAtom = atom(async (get) => {
  const egxEnabled = get(egxEnabledAtom)
  const rasterEnabled = get(rasterEnabledAtom)

  // Priority: EGX > Raster > Standard
  if (egxEnabled) {
    // Use EGX index buffer with manual edits applied
    const egxBuffer = await get(finalEgxIndexBufferAtom)
    if (egxBuffer) {
      return egxBuffer
    }
  }

  if (rasterEnabled) {
    // Use raster-optimized buffer with manual edits if available
    const rasterBuffer = get(finalRasterIndexBufferAtom)
    if (rasterBuffer) {
      return rasterBuffer
    }
  }

  // Fall back to standard preview buffer (with manual edits)
  return await get(finalPreviewIndexBufferAtom)
})

/**
 * Derived atom: returns the base raster palette (quantizedGlobalPalette)
 * This is the palette used as the base for all raster optimizations
 */
export const rasterBasePaletteAtom = atom((get) => {
  const result = get(rasterOptimizationResultAtom)
  return result?.quantizedGlobalPalette ?? null
})

/**
 * Action atom to clear all raster changes
 */
export const clearRasterChangesAtom = atom(null, (_get, set) => {
  set(rasterChangesAtom, [])
  set(rasterOptimizationResultAtom, null)
})

/**
 * Signature of all inputs that affect raster generation.
 * When any of these change, rasters should be cleared.
 *
 * Note: finalDithering is NOT included because it's applied AFTER raster optimization,
 * so changing it doesn't invalidate existing rasters.
 */
export const rasterInputSignatureAtom = atom((get) => {
  const image = get(imageAtom)
  const adjustments = get(configAtom)
  const strategy = get(paletteStrategyAtom)
  const modeConfig = get(effectiveModeConfigAtom)
  const hardware = get(cpcHardwareAtom)
  const selection = get(selectionAtom)

  // Create a signature from all relevant inputs
  return {
    imageId: image ? image.src : null,
    adjustments: JSON.stringify(adjustments),
    strategy,
    modeConfig: JSON.stringify(modeConfig),
    hardware,
    selection: JSON.stringify(selection)
  }
})

/**
 * Derived atom: returns true if rasters have been auto-generated
 * and the buffer dimensions match current mode config
 */
export const hasGeneratedRastersAtom = atom((get) => {
  const buffer = get(rasterIndexBufferAtom)
  if (!buffer) return false

  // Validate that buffer dimensions match current mode config
  const modeConfig = get(effectiveModeConfigAtom)
  return (
    buffer.width === modeConfig.width && buffer.height === modeConfig.height
  )
})

/**
 * Generate a unique ID for a new raster change
 */
export function generateChangeId(): string {
  return `raster-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`
}

/**
 * Action atom to add a new raster change
 */
export const addRasterChangeAtom = atom(
  null,
  (get, set, change: Omit<RasterChange, 'id'>) => {
    const changes = get(rasterChangesAtom)
    const newChange: RasterChange = {
      ...change,
      id: generateChangeId()
    }
    set(rasterChangesAtom, [...changes, newChange])
    return newChange.id
  }
)

/**
 * Action atom to update an existing raster change
 */
export const updateRasterChangeAtom = atom(
  null,
  (get, set, update: { id: string } & Partial<Omit<RasterChange, 'id'>>) => {
    const changes = get(rasterChangesAtom)
    const index = changes.findIndex((c) => c.id === update.id)
    if (index === -1) return false

    const updatedChanges = [...changes]
    updatedChanges[index] = { ...updatedChanges[index], ...update }
    set(rasterChangesAtom, updatedChanges)
    return true
  }
)

/**
 * Action atom to remove a raster change by ID
 */
export const removeRasterChangeAtom = atom(null, (get, set, id: string) => {
  const changes = get(rasterChangesAtom)
  set(
    rasterChangesAtom,
    changes.filter((c) => c.id !== id)
  )
})

/**
 * Helper to check for duplicate ink changes on a line
 */
function findDuplicateInkConflicts(
  lineChanges: RasterChange[],
  conflicts: string[]
): void {
  const inksSeen = new Map<number, string>()
  for (const change of lineChanges) {
    const existingId = inksSeen.get(change.inkIndex)
    if (existingId) {
      if (!conflicts.includes(existingId)) conflicts.push(existingId)
      if (!conflicts.includes(change.id)) conflicts.push(change.id)
    } else {
      inksSeen.set(change.inkIndex, change.id)
    }
  }
}

/**
 * Helper to check if a line exceeds max changes limit
 */
function findExcessChangesConflicts(
  lineChanges: RasterChange[],
  maxChangesPerLine: number,
  conflicts: string[]
): void {
  if (lineChanges.length > maxChangesPerLine) {
    for (const change of lineChanges) {
      if (!conflicts.includes(change.id)) conflicts.push(change.id)
    }
  }
}

/**
 * Helper to group changes by line number
 */
function groupChangesByLine(
  changes: RasterChange[]
): Map<number, RasterChange[]> {
  const byLine = new Map<number, RasterChange[]>()
  for (const change of changes) {
    const existing = byLine.get(change.line) || []
    existing.push(change)
    byLine.set(change.line, existing)
  }
  return byLine
}

/**
 * Derived atom: check for conflicts
 * - Same ink modified twice on same line = always a conflict
 * - Too many changes on same line = conflict based on user setting
 * Returns array of conflicting change IDs
 */
export const rasterConflictsAtom = atom((get) => {
  const changes = get(rasterChangesAtom)
  const maxChangesPerLine = get(rasterMaxChangesPerLineAtom)
  const conflicts: string[] = []

  const byLine = groupChangesByLine(changes)

  for (const [, lineChanges] of byLine) {
    findDuplicateInkConflicts(lineChanges, conflicts)
    findExcessChangesConflicts(lineChanges, maxChangesPerLine, conflicts)
  }

  return conflicts
})

/**
 * Derived atom: raster preview image
 * Returns an ImageData with raster effects applied, or null if rasters are disabled
 *
 * Uses the optimized rasterIndexBuffer when available (from auto-optimization),
 * otherwise falls back to the standard previewIndexBuffer.
 */
export const rasterPreviewImageAtom = atom(async (get) => {
  const enabled = get(rasterEnabledAtom)
  const changes = get(rasterChangesAtom)

  // Explicitly depend on optimization result AND version to force re-evaluation
  const optimizationResult = get(rasterOptimizationResultAtom)
  const version = get(rasterVersionAtom)

  logger.debug('[RASTER] rasterPreviewImageAtom evaluation', {
    enabled,
    changesCount: changes.length,
    hasOptimizationResult: !!optimizationResult,
    version
  })

  if (!enabled || changes.length === 0) {
    logger.debug('[RASTER] rasterPreviewImageAtom returning null', {
      reason: !enabled ? 'disabled' : 'no changes'
    })
    return null
  }

  // Get the export palette for rendering
  const exportPalette = await get(exportPaletteWithSlotsAtom)
  if (exportPalette.length === 0) {
    return null
  }

  // Get current mode config to validate dimensions
  const modeConfig = get(effectiveModeConfigAtom)

  // Check if we have an optimized raster index buffer (with manual edits applied)
  const rasterIndexBuffer = get(finalRasterIndexBufferAtom)

  if (rasterIndexBuffer) {
    logger.debug('[RASTER] Using optimized raster index buffer', {
      bufferWidth: rasterIndexBuffer.width,
      bufferHeight: rasterIndexBuffer.height,
      modeWidth: modeConfig.width,
      modeHeight: modeConfig.height
    })

    // Validate that buffer dimensions match current mode config
    if (
      rasterIndexBuffer.width !== modeConfig.width ||
      rasterIndexBuffer.height !== modeConfig.height
    ) {
      // Dimensions changed, buffer is stale - return null
      logger.debug('[RASTER] Buffer dimensions mismatch, returning null')
      return null
    }

    // Use the optimized index buffer from auto-optimization
    // This ensures pixel-to-ink mapping is consistent with raster changes
    const { buffer, width, height, palette } = rasterIndexBuffer
    const processor = get(imageProcessorAtom)
    if (processor) {
      try {
        const preview = processor.renderRasterPreview(
          buffer,
          width,
          height,
          palette,
          changes
        )
        logger.debug('[RASTER] GPU preview rendered successfully')
        // Force creation of new ImageData to avoid GPU cache issues
        return new ImageData(
          new Uint8ClampedArray(preview.data),
          preview.width,
          preview.height
        )
      } catch (error_) {
        // Fallback CPU if GPU path fails
        logger.warn('[RASTER] GPU preview failed, falling back to CPU', {
          error: error_
        })
      }
    }
    const preview = createRasterPreviewImageData(
      buffer,
      width,
      height,
      palette,
      changes
    )
    return preview
  }

  // Fallback to standard preview index buffer for manual raster changes
  const indexBufferData = await get(finalPreviewIndexBufferAtom)
  if (!indexBufferData) {
    return null
  }

  // Validate that buffer dimensions match current mode config
  if (
    indexBufferData.width !== modeConfig.width ||
    indexBufferData.height !== modeConfig.height
  ) {
    // Dimensions changed, buffer is stale - return null
    return null
  }

  const { buffer, width, height, palette } = indexBufferData
  const processor = get(imageProcessorAtom)
  if (processor) {
    try {
      return processor.renderRasterPreview(
        buffer,
        width,
        height,
        palette,
        changes
      )
    } catch (error_) {
      // Fallback CPU if GPU path fails
      logger.warn('[RASTER] GPU render failed, falling back to CPU', {
        error: error_
      })
    }
  }
  return createRasterPreviewImageData(buffer, width, height, palette, changes)
})

/**
 * Effective preview image atom: returns the appropriate preview based on mode.
 * Priority: Mode R > EGX > Raster > Manual Edits > Standard
 * Note: Mode R, EGX and Raster are mutually exclusive
 */
export const effectivePreviewImageAtom = atom(async (get) => {
  // Mode R takes priority and is incompatible with rasters/EGX
  const modeREnabled = get(modeREnabledAtom)
  if (modeREnabled) {
    const modeRPreview = await get(modeRPreviewImageAtom)
    if (modeRPreview) {
      return modeRPreview
    }
  }

  // EGX mode (line-by-line mode alternation)
  // Always use finalEgxPreviewImageAtom to include manual edits
  const egxEnabled = get(egxEnabledAtom)
  if (egxEnabled) {
    const finalEgxPreview = await get(finalEgxPreviewImageAtom)
    if (finalEgxPreview) {
      return finalEgxPreview
    }
  }

  // Force re-evaluation when raster version changes
  get(rasterVersionAtom)

  const rasterPreview = await get(rasterPreviewImageAtom)
  if (rasterPreview) {
    return rasterPreview
  }

  // Check if there are manual edits - if so, use final preview image
  const hasEdits = get(hasManualEditsAtom)
  if (hasEdits) {
    return await get(finalPreviewImageAtom)
  }

  return await get(previewImageAtom)
})

/**
 * Action atom to auto-optimize raster changes for CPC Plus Mode 1.
 * Analyzes each line of the image and generates optimal 4-color palettes.
 * Only available when CPC Plus hardware AND Mode 1 (4 colors) are selected.
 *
 * Uses the source image (before dithering) to detect the actual colors needed
 * per line, then generates raster changes to adapt the palette.
 *
 * @param options.resetChanges - If true, clears existing changes before optimizing (useful when dithering changes)
 */
export const autoOptimizeRasterAtom = atom(
  null,
  async (get, set, options?: { resetChanges?: boolean }) => {
    logger.time('[RASTER] autoOptimizeRasterAtom - Total')

    const modeConfig = get(effectiveModeConfigAtom)
    const hardware = get(cpcHardwareAtom)

    // Determine if we're in CPC Classic mode (27 colors) or Plus mode (4096 colors)
    const isClassicMode = hardware === 'classic'
    // CPC Classic palette is used to constrain colors to the 27 hardware colors
    const cpcClassicPalette = isClassicMode ? cpcPalette : undefined

    logger.time('[RASTER] Get positioned image')
    // Get the positioned normalized image (source colors, before dithering)
    // This gives us the TRUE colors of each pixel that we need to represent
    const sourceImage = await get(positionedNormalizedImageAtom)
    logger.timeEnd('[RASTER] Get positioned image')

    if (!sourceImage) {
      logger.timeEnd('[RASTER] autoOptimizeRasterAtom - Total')
      return { success: false, error: 'No image available' }
    }

    // Use dimensions from sourceImage
    const { width, height } = sourceImage

    // Detect Mode 0 CPC Plus (16 colors, Plus hardware)
    // In this mode, only 12 colors are fixed (indices 4-15), indices 0-3 are raster slots
    const isMode0Plus =
      modeConfig.nColors === MODE_0_TOTAL_COLORS && hardware === 'plus'

    logger.time('[RASTER] Get/calculate palette')
    // Get the global palette from the same quantization as non-raster mode
    const exportPalette = await get(exportPaletteWithSlotsAtom)

    let globalPalette: Vector<'RGB'>[]

    if (isMode0Plus) {
      // Mode 0 CPC Plus: take the 12 best colors (first 12) for fixed palette
      // These will be placed at indices 4-15 by the optimizer
      // Indices 0-3 are raster slots that will be filled dynamically per line
      globalPalette = exportPalette
        .filter((c) => c[0] !== -1)
        .slice(0, MODE_0_FIXED_COLORS)

      // Pad to 12 colors if needed
      while (globalPalette.length < MODE_0_FIXED_COLORS) {
        globalPalette.push([0, 0, 0])
      }

      logger.info(
        '[RASTER] Mode 0 Plus: using first 12 colors for fixed palette',
        {
          paletteLength: globalPalette.length
        }
      )
    } else {
      // Standard modes (Mode 1, Mode 2, Mode 0 Classic): use export palette directly
      globalPalette = exportPalette
        .filter((c) => c[0] !== -1)
        .slice(0, modeConfig.nColors)

      // Pad to nColors if needed
      while (globalPalette.length < modeConfig.nColors) {
        globalPalette.push([0, 0, 0])
      }
    }
    logger.timeEnd('[RASTER] Get/calculate palette')

    // Get raster dithering intensity
    const ditheringIntensity = get(rasterDitheringIntensityAtom)

    logger.time('[RASTER] Preprocess image')
    // PRE-PROCESS: Transform source image to have max nColors per line
    // This ensures smooth palette transitions and better raster optimization
    const preprocessedImage = preprocessImageForRaster(
      sourceImage,
      globalPalette,
      {
        ditheringIntensity,
        nColors: modeConfig.nColors,
        cpcClassicPalette
      }
    )
    logger.timeEnd('[RASTER] Preprocess image')

    // Get existing raster changes (without IDs for the algorithm)
    // If resetChanges is true, start fresh (useful when dithering intensity changes)
    const existingChanges = options?.resetChanges
      ? []
      : get(rasterChangesAtom).map(({ line, inkIndex, color }) => ({
          line,
          inkIndex,
          color
        }))

    // Get max changes per line setting, clamped to hardware limit
    // CPC Classic: max 2 changes per line
    // CPC Plus: max 4 changes per line
    // Also limited by number of colors in current mode
    const hardwareMax = isClassicMode ? 2 : 4
    const maxAllowedChanges = Math.min(modeConfig.nColors, hardwareMax)
    const maxChangesPerLine = Math.min(
      get(rasterMaxChangesPerLineAtom),
      maxAllowedChanges
    )

    logger.time('[RASTER] Optimize line palettes')
    // Generate optimized raster changes AND matching index buffer
    // - preprocessedImage: image with max nColors per line (smooth transitions)
    // - globalPalette: initial nColors palette (from same quantization as non-raster mode)
    // - useProvidedPalette: true to reuse the same palette calculation as non-raster mode
    // - Returns both raster changes and an index buffer where each pixel
    //   maps to its correct ink index based on per-line palettes
    const {
      changes: optimizedChanges,
      indexBuffer: optimizedIndexBuffer,
      quantizedGlobalPalette
    } = optimizeLinePalettesWithIndexBuffer(
      preprocessedImage,
      globalPalette,
      existingChanges,
      {
        maxChangesPerLine,
        nColors: modeConfig.nColors,
        cpcClassicPalette,
        useProvidedPalette: true // Use the same palette as non-raster mode
      }
    )
    logger.timeEnd('[RASTER] Optimize line palettes')

    // Filter out any changes that exceed the mode height (safety check)
    const maxLine = modeConfig.height - 1
    const validChanges = optimizedChanges.filter(
      (c: Omit<RasterChange, 'id'>) => c.line <= maxLine
    )

    // Convert to full RasterChange with IDs
    // Preserve IDs for existing changes, generate new IDs for new changes
    const existingIds = new Map(
      get(rasterChangesAtom).map((c) => [`${c.line}-${c.inkIndex}`, c.id])
    )
    const newChanges: RasterChange[] = validChanges.map(
      (change: Omit<RasterChange, 'id'>) => ({
        ...change,
        id:
          existingIds.get(`${change.line}-${change.inkIndex}`) ??
          generateChangeId()
      })
    )

    // Store the raw optimization result (without final dithering)
    // The final dithering will be applied by rasterIndexBufferAtom
    set(rasterOptimizationResultAtom, {
      optimizedIndexBuffer,
      quantizedGlobalPalette,
      rasterChanges: validChanges,
      preprocessedImage,
      width,
      height
    })

    // Replace all existing changes with optimized ones
    set(rasterChangesAtom, newChanges)

    // Increment version to force preview re-evaluation
    const currentVersion = get(rasterVersionAtom)
    set(rasterVersionAtom, currentVersion + 1)

    // Enable raster mode (mutually exclusive with Mode R and EGX)
    if (get(modeREnabledAtom)) {
      set(modeREnabledAtom, false)
    }
    if (get(egxEnabledAtom)) {
      set(egxEnabledAtom, false)
    }
    set(rasterEnabledAtom, true)

    logger.timeEnd('[RASTER] autoOptimizeRasterAtom - Total')
    logger.info(
      `[RASTER] Optimization complete: ${newChanges.length} changes, ${new Set(newChanges.map((c) => c.line)).size} lines affected`
    )

    return {
      success: true,
      changesCount: newChanges.length,
      linesAffected: new Set(newChanges.map((c) => c.line)).size
    }
  }
)
