import { atom } from 'jotai'
import type { Vector } from '@/libs/pixsaur-color/src/type'
import {
  createRasterPreviewImageData,
  optimizeLinePalettesWithIndexBuffer,
  preprocessImageForRaster
} from '@/libs/pixsaur-raster'
import type { RasterChange } from '@/libs/pixsaur-raster/types'
import {
  configAtom,
  cpcHardwareAtom,
  ditheringAtom,
  effectiveModeConfigAtom,
  paletteStrategyAtom
} from '../config/config'
import { imageAtom } from '../image/image'
import {
  exportPaletteWithSlotsAtom,
  positionedNormalizedImageAtom,
  previewImageAtom,
  previewIndexBufferAtom
} from '../preview/preview'
import {
  MAX_CHANGES_PER_LINE_DEFAULT,
  MAX_CHANGES_PER_LINE_PLUS_MODE1,
  rasterChangesAtom,
  rasterDitheringIntensityAtom,
  rasterEnabledAtom
} from './raster-config'

// Re-export primitive atoms for external use
export {
  MAX_CHANGES_PER_LINE_DEFAULT,
  MAX_CHANGES_PER_LINE_PLUS_MODE1,
  rasterChangesAtom,
  rasterDitheringIntensityAtom,
  rasterEnabledAtom
} from './raster-config'

/**
 * Optimized index buffer for raster rendering.
 * This is generated by the optimization algorithm and maps each pixel
 * to its correct ink index based on per-line palettes.
 * Also includes the quantized global palette used as starting point.
 */
export const rasterIndexBufferAtom = atom<{
  buffer: Uint8Array
  width: number
  height: number
  palette: Vector<'RGB'>[]
} | null>(null)

/**
 * Action atom to clear all raster changes
 */
export const clearRasterChangesAtom = atom(null, (_get, set) => {
  set(rasterChangesAtom, [])
  set(rasterIndexBufferAtom, null)
})

/**
 * Atom that tracks the "signature" of inputs that should trigger raster clear.
 * When any of these change, rasters should be cleared.
 */
export const rasterInputSignatureAtom = atom((get) => {
  const image = get(imageAtom)
  const adjustments = get(configAtom)
  const strategy = get(paletteStrategyAtom)
  const dithering = get(ditheringAtom)

  // Create a signature from all relevant inputs
  return {
    imageId: image ? image.src : null,
    adjustments: JSON.stringify(adjustments),
    strategy,
    ditheringMode: dithering.mode,
    ditheringIntensity: dithering.intensity
  }
})

/**
 * @deprecated Use rasterChangesAtom instead
 */
export const rasterRangesAtom = rasterChangesAtom

/**
 * Generate a unique ID for a new raster change
 */
export function generateChangeId(): string {
  return `raster-${Date.now()}-${Math.random().toString(36).slice(2, 9)}`
}

/**
 * @deprecated Use generateChangeId instead
 */
export const generateRangeId = generateChangeId

/**
 * Action atom to add a new raster change
 */
export const addRasterChangeAtom = atom(
  null,
  (get, set, change: Omit<RasterChange, 'id'>) => {
    const changes = get(rasterChangesAtom)
    const newChange: RasterChange = {
      ...change,
      id: generateChangeId()
    }
    set(rasterChangesAtom, [...changes, newChange])
    return newChange.id
  }
)

/**
 * @deprecated Use addRasterChangeAtom instead
 */
export const addRasterRangeAtom = addRasterChangeAtom

/**
 * Action atom to update an existing raster change
 */
export const updateRasterChangeAtom = atom(
  null,
  (get, set, update: { id: string } & Partial<Omit<RasterChange, 'id'>>) => {
    const changes = get(rasterChangesAtom)
    const index = changes.findIndex((c) => c.id === update.id)
    if (index === -1) return false

    const updatedChanges = [...changes]
    updatedChanges[index] = { ...updatedChanges[index], ...update }
    set(rasterChangesAtom, updatedChanges)
    return true
  }
)

/**
 * @deprecated Use updateRasterChangeAtom instead
 */
export const updateRasterRangeAtom = updateRasterChangeAtom

/**
 * Action atom to remove a raster change by ID
 */
export const removeRasterChangeAtom = atom(null, (get, set, id: string) => {
  const changes = get(rasterChangesAtom)
  set(
    rasterChangesAtom,
    changes.filter((c) => c.id !== id)
  )
})

/**
 * @deprecated Use removeRasterChangeAtom instead
 */
export const removeRasterRangeAtom = removeRasterChangeAtom

/**
 * @deprecated Use clearRasterChangesAtom instead
 */
export const clearRasterRangesAtom = clearRasterChangesAtom

/**
 * Derived atom: check for conflicts
 * - Same ink modified twice on same line = always a conflict
 * - Too many changes on same line = conflict
 *   - CPC Plus Mode 1 allows 4 changes per line
 *   - All other modes allow only 1 change per line
 * Returns array of conflicting change IDs
 */
export const rasterConflictsAtom = atom((get) => {
  const changes = get(rasterChangesAtom)
  const hardware = get(cpcHardwareAtom)
  const modeConfig = get(effectiveModeConfigAtom)

  // Only CPC Plus + Mode 1 (4 colors) allows 4 ink changes per line
  const isPlusMode1 = hardware === 'plus' && modeConfig.nColors === 4
  const maxChangesPerLine = isPlusMode1
    ? MAX_CHANGES_PER_LINE_PLUS_MODE1
    : MAX_CHANGES_PER_LINE_DEFAULT
  const conflicts: string[] = []

  // Group by line
  const byLine = new Map<number, RasterChange[]>()
  for (const change of changes) {
    const existing = byLine.get(change.line) || []
    existing.push(change)
    byLine.set(change.line, existing)
  }

  // Check conflicts for each line
  for (const [, lineChanges] of byLine) {
    // Check for same ink modified twice on same line
    const inksSeen = new Map<number, string>()
    for (const change of lineChanges) {
      if (inksSeen.has(change.inkIndex)) {
        // Conflict: same ink modified twice on same line
        const existingId = inksSeen.get(change.inkIndex)!
        if (!conflicts.includes(existingId)) conflicts.push(existingId)
        if (!conflicts.includes(change.id)) conflicts.push(change.id)
      } else {
        inksSeen.set(change.inkIndex, change.id)
      }
    }

    // Check for too many changes on same line
    if (lineChanges.length > maxChangesPerLine) {
      // All changes on this line are in conflict (exceeds hardware limit)
      for (const change of lineChanges) {
        if (!conflicts.includes(change.id)) conflicts.push(change.id)
      }
    }
  }

  return conflicts
})

/**
 * Derived atom: raster preview image
 * Returns an ImageData with raster effects applied, or null if rasters are disabled
 *
 * Uses the optimized rasterIndexBuffer when available (from auto-optimization),
 * otherwise falls back to the standard previewIndexBuffer.
 */
export const rasterPreviewImageAtom = atom(async (get) => {
  const enabled = get(rasterEnabledAtom)
  const changes = get(rasterChangesAtom)

  if (!enabled || changes.length === 0) {
    return null
  }

  // Get the export palette for rendering
  const exportPalette = await get(exportPaletteWithSlotsAtom)
  if (exportPalette.length === 0) {
    return null
  }

  // Check if we have an optimized raster index buffer
  const rasterIndexBuffer = get(rasterIndexBufferAtom)

  if (rasterIndexBuffer) {
    // Use the optimized index buffer from auto-optimization
    // This ensures pixel-to-ink mapping is consistent with raster changes
    const { buffer, width, height, palette } = rasterIndexBuffer
    return createRasterPreviewImageData(buffer, width, height, palette, changes)
  }

  // Fallback to standard preview index buffer for manual raster changes
  const indexBufferData = await get(previewIndexBufferAtom)
  if (!indexBufferData) {
    return null
  }

  const { buffer, width, height, palette } = indexBufferData
  return createRasterPreviewImageData(buffer, width, height, palette, changes)
})

/**
 * Effective preview image atom: returns raster preview when enabled, otherwise normal preview
 */
export const effectivePreviewImageAtom = atom(async (get) => {
  const rasterPreview = await get(rasterPreviewImageAtom)
  if (rasterPreview) {
    return rasterPreview
  }

  return await get(previewImageAtom)
})

/**
 * Action atom to auto-optimize raster changes for CPC Plus Mode 1.
 * Analyzes each line of the image and generates optimal 4-color palettes.
 * Only available when CPC Plus hardware AND Mode 1 (4 colors) are selected.
 *
 * Uses the source image (before dithering) to detect the actual colors needed
 * per line, then generates raster changes to adapt the palette.
 *
 * @param options.resetChanges - If true, clears existing changes before optimizing (useful when dithering changes)
 */
export const autoOptimizeRasterAtom = atom(
  null,
  async (get, set, options?: { resetChanges?: boolean }) => {
    const hardware = get(cpcHardwareAtom)
    const modeConfig = get(effectiveModeConfigAtom)

    // Only works for CPC Plus + Mode 1
    if (hardware !== 'plus' || modeConfig.nColors !== 4) {
      return { success: false, error: 'Only available for CPC Plus Mode 1' }
    }

    // Get the positioned normalized image (source colors, before dithering)
    // This gives us the TRUE colors of each pixel that we need to represent
    const sourceImage = await get(positionedNormalizedImageAtom)
    if (!sourceImage) {
      return { success: false, error: 'No image available' }
    }

    // Use dimensions from sourceImage
    const { width, height } = sourceImage

    // Get the global palette (4 colors for Mode 1)
    // Note: The optimization algorithm now extracts palette directly from source image,
    // but we still need this for the initial API compatibility
    const exportPalette = await get(exportPaletteWithSlotsAtom)

    // Filter out invalid slots and take first 4 colors
    // If no valid colors, we'll use a placeholder - the algorithm will extract from image
    const globalPalette = exportPalette.filter((c) => c[0] !== -1).slice(0, 4)

    // Pad to 4 colors if needed (algorithm will override with extracted colors anyway)
    while (globalPalette.length < 4) {
      globalPalette.push([0, 0, 0])
    }

    // Get raster dithering intensity
    const ditheringIntensity = get(rasterDitheringIntensityAtom)

    // PRE-PROCESS: Transform source image to have max 4 colors per line
    // This ensures smooth palette transitions and better raster optimization
    const preprocessedImage = preprocessImageForRaster(
      sourceImage,
      globalPalette,
      {
        ditheringIntensity
      }
    )

    // Get existing raster changes (without IDs for the algorithm)
    // If resetChanges is true, start fresh (useful when dithering intensity changes)
    const existingChanges = options?.resetChanges
      ? []
      : get(rasterChangesAtom).map(({ line, inkIndex, color }) => ({
          line,
          inkIndex,
          color
        }))

    // Generate optimized raster changes AND matching index buffer
    // - preprocessedImage: image with max 4 colors per line (smooth transitions)
    // - globalPalette: initial 4-color palette
    // - Returns both raster changes and an index buffer where each pixel
    //   maps to its correct ink index based on per-line palettes
    const {
      changes: optimizedChanges,
      indexBuffer: optimizedIndexBuffer,
      quantizedGlobalPalette
    } = optimizeLinePalettesWithIndexBuffer(
      preprocessedImage,
      globalPalette,
      existingChanges
    )

    // Filter out any changes that exceed the mode height (safety check)
    const maxLine = modeConfig.height - 1
    const validChanges = optimizedChanges.filter(
      (c: Omit<RasterChange, 'id'>) => c.line <= maxLine
    )

    // Convert to full RasterChange with IDs
    // Preserve IDs for existing changes, generate new IDs for new changes
    const existingIds = new Map(
      get(rasterChangesAtom).map((c) => [`${c.line}-${c.inkIndex}`, c.id])
    )
    const newChanges: RasterChange[] = validChanges.map(
      (change: Omit<RasterChange, 'id'>) => ({
        ...change,
        id:
          existingIds.get(`${change.line}-${change.inkIndex}`) ??
          generateChangeId()
      })
    )

    // Store the optimized index buffer and palette for rendering
    set(rasterIndexBufferAtom, {
      buffer: optimizedIndexBuffer,
      width,
      height,
      palette: quantizedGlobalPalette
    })

    // Replace all existing changes with optimized ones
    set(rasterChangesAtom, newChanges)

    // Enable raster mode
    set(rasterEnabledAtom, true)

    return {
      success: true,
      changesCount: newChanges.length,
      linesAffected: new Set(newChanges.map((c) => c.line)).size
    }
  }
)
