/**
 * Raster Index Buffer Atoms
 *
 * Manages the index buffers used for raster rendering:
 * - Raw optimization result storage
 * - Dithering application
 * - Manual edits integration
 */

import { atom } from 'jotai'
import type { Vector } from '@/libs/pixsaur-color/src/type'
import { applyDitheringWithRaster } from '@/libs/pixsaur-raster'
import type { RasterChange } from '@/libs/pixsaur-raster/types'
import { ditheringAtom, effectiveModeConfigAtom } from '../config/config'
import {
  applyManualEditsToBuffer,
  manualPixelEditsAtom
} from '../preview/preview'

/**
 * Version counter that increments each time raster optimization completes.
 * Used to force re-evaluation of preview atoms even if data dimensions are the same.
 */
export const rasterVersionAtom = atom(0)

/**
 * Raw optimization result from the raster algorithm (without final dithering).
 * This is generated by the optimization algorithm and stores:
 * - optimizedIndexBuffer: pixel indices based on raster changes (no final dithering)
 * - quantizedGlobalPalette: the base palette before any raster changes
 * - rasterChanges: the array of raster changes (without IDs)
 * - preprocessedImage: the source image used for optimization (for dithering)
 * - dimensions: width and height
 */
export const rasterOptimizationResultAtom = atom<{
  optimizedIndexBuffer: Uint8Array
  quantizedGlobalPalette: Vector<'RGB'>[]
  rasterChanges: Array<Omit<RasterChange, 'id'>>
  preprocessedImage: ImageData
  width: number
  height: number
} | null>(null)

/**
 * Optimized index buffer for raster rendering with final dithering applied.
 * This is a derived atom that:
 * 1. Takes the raw optimization result (without final dithering)
 * 2. Applies the user-configured final dithering respecting per-line palettes
 * 3. Returns the final index buffer ready for rendering
 *
 * Automatically recalculates when dithering config changes.
 */
export const rasterIndexBufferAtom = atom((get) => {
  const result = get(rasterOptimizationResultAtom)
  if (!result) return null

  const ditheringConfig = get(ditheringAtom)
  const modeConfig = get(effectiveModeConfigAtom)

  const {
    optimizedIndexBuffer,
    quantizedGlobalPalette,
    rasterChanges,
    preprocessedImage,
    width,
    height
  } = result

  // If no dithering configured, return the optimized buffer as-is
  if (ditheringConfig.mode === 'none' || ditheringConfig.intensity === 0) {
    return {
      buffer: optimizedIndexBuffer,
      width,
      height,
      palette: quantizedGlobalPalette
    }
  }

  // Apply final dithering with per-line palettes
  const finalIndexBuffer = applyDitheringWithRaster(
    preprocessedImage,
    quantizedGlobalPalette,
    rasterChanges,
    ditheringConfig,
    modeConfig.nColors
  )

  return {
    buffer: finalIndexBuffer,
    width,
    height,
    palette: quantizedGlobalPalette
  }
})

/**
 * Final raster index buffer with manual pixel edits applied.
 * Applies manual edits on top of the raster-optimized buffer.
 */
export const finalRasterIndexBufferAtom = atom((get) => {
  const rasterBuffer = get(rasterIndexBufferAtom)
  if (!rasterBuffer) return null

  const edits = get(manualPixelEditsAtom)
  return applyManualEditsToBuffer(rasterBuffer, edits)
})

/**
 * Derived atom: returns the base raster palette (quantizedGlobalPalette)
 * This is the palette used as the base for all raster optimizations
 */
export const rasterBasePaletteAtom = atom((get) => {
  const result = get(rasterOptimizationResultAtom)
  return result?.quantizedGlobalPalette ?? null
})

/**
 * Derived atom: returns true if rasters have been auto-generated
 * and the buffer dimensions match current mode config
 */
export const hasGeneratedRastersAtom = atom((get) => {
  const buffer = get(rasterIndexBufferAtom)
  if (!buffer) return false

  // Validate that buffer dimensions match current mode config
  const modeConfig = get(effectiveModeConfigAtom)
  return (
    buffer.width === modeConfig.width && buffer.height === modeConfig.height
  )
})
