/**
 * Mode R Export Functions
 *
 * Mode R generates two SCR images (Frame A and Frame B) with two independent palettes.
 * These are displayed alternately at 50Hz with horizontal sub-pixel shifts to create
 * the perception of doubled horizontal resolution.
 */

import type JSZip from 'jszip'
import type { CpcModeConfig } from '@/app/store/config/types'
import type { Vector } from '@/libs/pixsaur-color/src/type'
import type { CPCHardware } from '@/libs/types'
import { firmwareToHardware } from '../cpc-format'
import { paletteToCPCPlusValues } from '../cpc-plus-format'
import { exportLinearAsm } from '../export-linear-asm/export-linear.asm'
import { exportSCR } from '../export-scr/export-scr'
import { rgbToFirmwareIndex } from '../raster-format'
import { toASMData } from '../to-asm-data'
import type { ExportConfig } from '../types'

export interface ModeRExportData {
  indexBufferA: Uint8Array
  indexBufferB: Uint8Array
  paletteA: Vector<'RGB'>[]
  paletteB: Vector<'RGB'>[]
}

/**
 * Generate header comment for Mode R ASM files
 */
function getModeRHeader(
  modeConfig: CpcModeConfig,
  frame: 'A' | 'B',
  isPlus: boolean,
  isLinear = false
): string {
  const hw = isPlus ? 'CPC Plus' : 'CPC Classic'
  const format = isLinear ? 'Linear' : 'SCR'
  const overscanNote = modeConfig.overscan ? ' (Overscan)' : ''
  return `; Mode R Frame ${frame} - ${hw} - ${format}${overscanNote}
; Dimensions: ${modeConfig.width}x${modeConfig.height}
; Mode: ${modeConfig.mode} (16 colors)
; Generated by Pixsaur
;
`
}

/**
 * Generate palette ASM for Mode R (both palettes in one file)
 * Includes both firmware indices and hardware (Gate Array) codes
 */
function generateModeRPaletteAsmClassic(
  paletteA: number[],
  paletteB: number[]
): string {
  // Convert firmware to hardware codes
  const hardwareA = paletteA.map((fw) => firmwareToHardware[fw] ?? 0x54)
  const hardwareB = paletteB.map((fw) => firmwareToHardware[fw] ?? 0x54)

  let asm = `; Mode R Palettes - CPC Classic
; Two 16-color palettes for alternating frames
; Generated by Pixsaur
;
; Firmware indices (for BASIC INK command)
; Hardware codes (Gate Array values for direct hardware access)
;

; ========== FIRMWARE INDICES ==========

ModeR_PaletteA_Firmware:
`
  for (let i = 0; i < paletteA.length; i++) {
    asm += `    db ${paletteA[i]}  ; Ink ${i}\n`
  }

  asm += `
ModeR_PaletteB_Firmware:
`
  for (let i = 0; i < paletteB.length; i++) {
    asm += `    db ${paletteB[i]}  ; Ink ${i}\n`
  }

  asm += `

; ========== HARDWARE CODES (Gate Array) ==========

ModeR_PaletteA_Hardware:
`
  for (let i = 0; i < hardwareA.length; i++) {
    asm += `    db #${hardwareA[i].toString(16).toUpperCase().padStart(2, '0')}  ; Ink ${i}\n`
  }

  asm += `
ModeR_PaletteB_Hardware:
`
  for (let i = 0; i < hardwareB.length; i++) {
    asm += `    db #${hardwareB[i].toString(16).toUpperCase().padStart(2, '0')}  ; Ink ${i}\n`
  }

  return asm
}

/**
 * Generate palette ASM for Mode R CPC Plus (12-bit values)
 */
function generateModeRPaletteAsmPlus(
  paletteA: number[],
  paletteB: number[]
): string {
  let asm = `; Mode R Palettes - CPC Plus (12-bit)
; Two 16-color palettes for alternating frames
; Format: #0GRB (4 bits per channel)
; Generated by Pixsaur
;

ModeR_PaletteA:
`
  for (let i = 0; i < paletteA.length; i++) {
    asm += `    dw #${paletteA[i].toString(16).toUpperCase().padStart(3, '0')}  ; Ink ${i}\n`
  }

  asm += `
ModeR_PaletteB:
`
  for (let i = 0; i < paletteB.length; i++) {
    asm += `    dw #${paletteB[i].toString(16).toUpperCase().padStart(3, '0')}  ; Ink ${i}\n`
  }

  return asm
}

/**
 * Export Mode R data to ZIP file
 */
export async function exportModeRToZip(
  zip: JSZip,
  data: ModeRExportData,
  modeConfig: CpcModeConfig,
  cpcHardware: CPCHardware,
  config: ExportConfig,
  baseLabel: string
): Promise<void> {
  const isPlus = cpcHardware === 'plus'

  // Convert palettes to firmware indices
  const paletteAFirmware = data.paletteA.map((c) =>
    rgbToFirmwareIndex(c[0], c[1], c[2])
  )
  const paletteBFirmware = data.paletteB.map((c) =>
    rgbToFirmwareIndex(c[0], c[1], c[2])
  )

  // Check if mode is standard (required for SCR format)
  // Mode R uses Mode 0 dimensions: 160x200 without overscan
  const isStandardMode =
    !modeConfig.overscan &&
    modeConfig.mode === 0 &&
    modeConfig.width === 160 &&
    modeConfig.height === 200

  // Generate SCR files for both frames (only for standard mode)
  if (config.content.includeSCR && isStandardMode) {
    // Frame A
    const scrA = exportSCR(data.indexBufferA, modeConfig)
    const asmResultA = toASMData(scrA, `${baseLabel}_frameA`)
    if (typeof asmResultA === 'string') {
      const headerA = getModeRHeader(modeConfig, 'A', isPlus)
      zip.file(`${baseLabel}_frameA.asm`, headerA + asmResultA)
    }

    // Frame B
    const scrB = exportSCR(data.indexBufferB, modeConfig)
    const asmResultB = toASMData(scrB, `${baseLabel}_frameB`)
    if (typeof asmResultB === 'string') {
      const headerB = getModeRHeader(modeConfig, 'B', isPlus)
      zip.file(`${baseLabel}_frameB.asm`, headerB + asmResultB)
    }
  }

  // Generate palette file
  if (config.content.includePalettes) {
    if (isPlus) {
      const paletteAPlusValues = paletteToCPCPlusValues(
        data.paletteA.map((c) => [c[0], c[1], c[2]] as [number, number, number])
      )
      const paletteBPlusValues = paletteToCPCPlusValues(
        data.paletteB.map((c) => [c[0], c[1], c[2]] as [number, number, number])
      )
      const paletteAsm = generateModeRPaletteAsmPlus(
        paletteAPlusValues,
        paletteBPlusValues
      )
      zip.file(`${baseLabel}_palettes.asm`, paletteAsm)
    } else {
      const paletteAsm = generateModeRPaletteAsmClassic(
        paletteAFirmware,
        paletteBFirmware
      )
      zip.file(`${baseLabel}_palettes.asm`, paletteAsm)
    }
  }

  // Generate linear data if requested (or if overscan - SCR not available)
  if (config.content.includeLinear || !isStandardMode) {
    const linearHeaderA = getModeRHeader(modeConfig, 'A', isPlus, true)
    const linearHeaderB = getModeRHeader(modeConfig, 'B', isPlus, true)

    // Encode pixel data (2 pixels per byte in Mode 0)
    const encodedA = exportLinearAsm(data.indexBufferA, modeConfig)
    const encodedB = exportLinearAsm(data.indexBufferB, modeConfig)

    // Frame A linear
    const linearAsmA = toASMData(encodedA, `${baseLabel}_linear_frameA`)
    if (typeof linearAsmA === 'string') {
      zip.file(`${baseLabel}_linear_frameA.asm`, linearHeaderA + linearAsmA)
    } else {
      // Multiple chunks for large data (overscan)
      for (const chunk of linearAsmA) {
        zip.file(chunk.filename, linearHeaderA + chunk.content)
      }
    }

    // Frame B linear
    const linearAsmB = toASMData(encodedB, `${baseLabel}_linear_frameB`)
    if (typeof linearAsmB === 'string') {
      zip.file(`${baseLabel}_linear_frameB.asm`, linearHeaderB + linearAsmB)
    } else {
      // Multiple chunks for large data (overscan)
      for (const chunk of linearAsmB) {
        zip.file(chunk.filename, linearHeaderB + chunk.content)
      }
    }
  }
}

/**
 * Prepare Mode R data for CPC Playground export
 */
export function prepareModeRForPlayground(
  data: ModeRExportData,
  modeConfig: CpcModeConfig,
  cpcHardware: CPCHardware
): {
  scrA: Uint8Array
  scrB: Uint8Array
  paletteAFirmware?: number[]
  paletteBFirmware?: number[]
  paletteAPlus?: number[]
  paletteBPlus?: number[]
} {
  const isPlus = cpcHardware === 'plus'

  const scrA = exportSCR(data.indexBufferA, modeConfig)
  const scrB = exportSCR(data.indexBufferB, modeConfig)

  if (isPlus) {
    return {
      scrA,
      scrB,
      paletteAPlus: paletteToCPCPlusValues(
        data.paletteA.map((c) => [c[0], c[1], c[2]] as [number, number, number])
      ),
      paletteBPlus: paletteToCPCPlusValues(
        data.paletteB.map((c) => [c[0], c[1], c[2]] as [number, number, number])
      )
    }
  } else {
    return {
      scrA,
      scrB,
      paletteAFirmware: data.paletteA.map((c) =>
        rgbToFirmwareIndex(c[0], c[1], c[2])
      ),
      paletteBFirmware: data.paletteB.map((c) =>
        rgbToFirmwareIndex(c[0], c[1], c[2])
      )
    }
  }
}
