import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { DskImage } from '@/app/store/dsk-workspace/dsk-workspace'
import { generateDskFilenames } from '@/components/dsk-workspace/dsk-workspace-utils'

/**
 * Generate PDF README for DSK export
 * Converts markdown content to formatted PDF
 */
export function generateDskReadmePdf(
  images: DskImage[],
  dskFilename: string
): Blob {
  const doc = new jsPDF()
  let yPosition = 20

  // Title
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text(dskFilename, 20, yPosition)
  yPosition += 10

  // Generation date
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
  doc.text(`Generated by Pixsaur on ${date}`, 20, yPosition)
  yPosition += 15

  // Contents section
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('Contents', 20, yPosition)
  yPosition += 8

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(
    `This DSK contains ${images.length} image(s) converted for Amstrad CPC.`,
    20,
    yPosition
  )
  yPosition += 10

  // Files table
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Files', 20, yPosition)
  yPosition += 5

  // Build files list including chunks for custom dimensions
  const filesTableData: string[][] = []
  for (let i = 0; i < images.length; i++) {
    const image = images[i]
    const imageIndex = i + 1
    const filenames = generateDskFilenames(
      imageIndex,
      image.width,
      image.height,
      image.mode,
      image.overscan
    )
    const hardware = image.cpcHardware === 'plus' ? 'CPC Plus' : 'CPC Classic'
    const mode = `Mode ${image.mode}`
    const dimensions = `${image.width}×${image.height}`
    const colors = String(image.nColors)

    if (filenames.length === 1) {
      // Single file (standard or small custom)
      filesTableData.push([filenames[0], hardware, mode, dimensions, colors])
    } else {
      // Multiple chunks - show main file with chunk count
      filesTableData.push([
        `${filenames[0].replace(/_1\.BIN$/, '.BIN')} (${filenames.length} chunks)`,
        hardware,
        mode,
        dimensions,
        colors
      ])
    }
  }

  autoTable(doc, {
    startY: yPosition,
    head: [['Filename', 'Hardware', 'Mode', 'Dimensions', 'Colors']],
    body: filesTableData,
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185] },
    styles: { fontSize: 9 }
  })

  yPosition = (doc as any).lastAutoTable.finalY + 10

  // How to use section
  if (yPosition > 250) {
    doc.addPage()
    yPosition = 20
  }

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('How to use', 20, yPosition)
  yPosition += 8

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Standard SCR files (from BASIC):', 20, yPosition)
  yPosition += 6

  doc.setFont('courier', 'normal')
  doc.setFontSize(9)
  doc.text('MEMORY &7FFF', 25, yPosition)
  yPosition += 5
  doc.text('LOAD"LOADER.BIN",&8000', 25, yPosition)
  yPosition += 5
  doc.text('A$="IMG1.SCR"', 25, yPosition)
  yPosition += 5
  doc.text('CALL &8000, @A$', 25, yPosition)
  yPosition += 8

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  const loaderText =
    'The loader automatically detects CPC Classic or CPC Plus format and applies the appropriate palette. This only works for standard .SCR files.'
  const splitText = doc.splitTextToSize(loaderText, 170)
  doc.text(splitText, 20, yPosition)
  yPosition += 6 * splitText.length + 8

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Custom dimension files (.BIN):', 20, yPosition)
  yPosition += 6

  const customText =
    'Files with custom dimensions are exported as raw linear data (.BIN format) and may be split into multiple chunks if larger than 16KB. These files require custom loading code tailored to your specific dimensions and usage.'
  const splitCustomText = doc.splitTextToSize(customText, 170)
  doc.text(splitCustomText, 20, yPosition)
  yPosition += 6 * splitCustomText.length + 2

  // SCR File Format section
  if (yPosition > 230) {
    doc.addPage()
    yPosition = 20
  }

  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('File Formats', 20, yPosition)
  yPosition += 8

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Standard SCR Format (160x200, 320x200, 640x200)', 20, yPosition)
  yPosition += 8

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(
    'Each .SCR file is 16KB (16384 bytes) with embedded metadata in the first 2KB block:',
    20,
    yPosition
  )
  yPosition += 10

  // Memory Layout table
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Memory Layout', 20, yPosition)
  yPosition += 5

  autoTable(doc, {
    startY: yPosition,
    head: [['Offset', 'Size', 'Description']],
    body: [['#0000-#3FFF', '16384', 'Screen data (pixel data in CPC format)']],
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185] },
    styles: { fontSize: 9 }
  })

  yPosition = (doc as any).lastAutoTable.finalY + 10

  // CPC Classic Format
  if (yPosition > 200) {
    doc.addPage()
    yPosition = 20
  }

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('CPC Classic Format (Metadata Area)', 20, yPosition)
  yPosition += 5

  autoTable(doc, {
    startY: yPosition,
    head: [['Offset', 'Size', 'Description']],
    body: [
      ['2000', '1', 'Border color (firmware index)'],
      ['2001-2016', '16', 'Palette colors (firmware indices)'],
      ['2017', '1', 'Border color (hardware value)'],
      ['2018-2033', '16', 'Palette colors (hardware values)'],
      ['2034', '1', 'Graphics mode (0, 1, or 2)'],
      ['2035', '1', 'Hardware type (0 = Classic)'],
      ['2036-2047', '12', 'Reserved/unused']
    ],
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185] },
    styles: { fontSize: 8 }
  })

  yPosition = (doc as any).lastAutoTable.finalY + 10

  // CPC Plus Format
  if (yPosition > 200) {
    doc.addPage()
    yPosition = 20
  }

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('CPC Plus Format (Metadata Area)', 20, yPosition)
  yPosition += 5

  autoTable(doc, {
    startY: yPosition,
    head: [['Offset', 'Size', 'Description']],
    body: [
      ['2000-2001', '2', 'Border color (16-bit little-endian, GRB format)'],
      [
        '2002-2033',
        '32',
        '16 palette colors (16×2 bytes, little-endian, GRB format)'
      ],
      ['2034', '1', 'Graphics mode (0, 1, or 2)'],
      ['2035', '1', 'Hardware type (1 = Plus)'],
      ['2036-2047', '12', 'Reserved/unused']
    ],
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185] },
    styles: { fontSize: 8 }
  })

  yPosition = (doc as any).lastAutoTable.finalY + 8

  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.text('Note:', 20, yPosition)
  doc.setFont('helvetica', 'normal')
  yPosition += 5
  doc.text(
    'CPC Plus colors use 4 bits per component in GRB order:',
    20,
    yPosition
  )
  yPosition += 5
  doc.setFont('courier', 'normal')
  doc.text(
    'Format: 0000 GGGG RRRR BBBB (12-bit color from 4096 colors)',
    25,
    yPosition
  )
  yPosition += 5
  doc.setFont('helvetica', 'normal')
  doc.text('Stored as 16-bit little-endian values', 25, yPosition)
  yPosition += 10

  // Custom BIN Format section
  if (yPosition > 200) {
    doc.addPage()
    yPosition = 20
  }

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Custom BIN Format (Non-standard dimensions)', 20, yPosition)
  yPosition += 8

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const binFormatText =
    'Files with custom dimensions (e.g., overscan, custom resolutions) are exported as raw linear pixel data without any metadata. Each file contains only the raw CPC screen data organized sequentially.'
  const splitBinFormat = doc.splitTextToSize(binFormatText, 170)
  doc.text(splitBinFormat, 20, yPosition)
  yPosition += 6 * splitBinFormat.length + 8

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Characteristics', 20, yPosition)
  yPosition += 5

  autoTable(doc, {
    startY: yPosition,
    head: [['Property', 'Description']],
    body: [
      ['Extension', '.BIN'],
      ['Format', 'Raw linear pixel data (no metadata)'],
      ['Size', 'width / pixelsPerByte × height'],
      ['Chunking', 'Files > 16KB split into multiple chunks (_1, _2, etc.)'],
      ['Palette', 'Not embedded - must be set by your code'],
      ['Usage', 'Requires custom loading code']
    ],
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185] },
    styles: { fontSize: 9 }
  })

  yPosition = (doc as any).lastAutoTable.finalY + 8

  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  const pixelsPerByteText =
    'pixelsPerByte = Mode 0: 2 pixels/byte, Mode 1: 4 pixels/byte, Mode 2: 8 pixels/byte'
  doc.text(pixelsPerByteText, 20, yPosition)
  yPosition += 10

  // Palette Information
  if (yPosition > 230) {
    doc.addPage()
    yPosition = 20
  }

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Palette Information', 20, yPosition)
  yPosition += 8

  for (const [index, image] of images.entries()) {
    if (yPosition > 250) {
      doc.addPage()
      yPosition = 20
    }

    const imageIndex = index + 1
    const filenames = generateDskFilenames(
      imageIndex,
      image.width,
      image.height,
      image.mode,
      image.overscan
    )
    const displayFilename =
      filenames.length === 1
        ? filenames[0]
        : `${filenames[0].replace(/_1\.BIN$/, '.BIN')} (${filenames.length} chunks)`

    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text(
      `${displayFilename} (${image.cpcHardware === 'plus' ? 'CPC Plus' : 'CPC Classic'})`,
      20,
      yPosition
    )
    yPosition += 6

    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')

    if (
      image.cpcHardware === 'classic' &&
      image.paletteFirmware &&
      image.paletteFirmware.length > 0
    ) {
      doc.text('Firmware indices:', 20, yPosition)
      yPosition += 5
      doc.setFont('courier', 'normal')
      const paletteText = `[${image.paletteFirmware.join(', ')}]`
      const splitPalette = doc.splitTextToSize(paletteText, 170)
      doc.text(splitPalette, 25, yPosition)
      yPosition += 5 * splitPalette.length + 5
    } else if (
      image.cpcHardware === 'plus' &&
      image.palettePlus &&
      image.palettePlus.length > 0
    ) {
      doc.text('Hardware values (GRB format):', 20, yPosition)
      yPosition += 5
      doc.setFont('courier', 'normal')
      const paletteText = `[${image.palettePlus
        .map((v) => `#${v.toString(16).toUpperCase().padStart(3, '0')}`)
        .join(', ')}]`
      const splitPalette = doc.splitTextToSize(paletteText, 170)
      doc.text(splitPalette, 25, yPosition)
      yPosition += 5 * splitPalette.length + 8
    }

    doc.setFont('helvetica', 'normal')
  }

  // Footer
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.text(
      'Generated with Pixsaur (https://pixsaur.iiivan.org/) - Image converter for Amstrad CPC',
      20,
      285
    )
    doc.setFont('helvetica', 'normal')
    doc.text(`Page ${i} of ${totalPages}`, 180, 285)
  }

  return doc.output('blob')
}
