import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import type { DskImage } from '@/app/store/dsk-workspace/dsk-workspace'

/**
 * Generate PDF README for DSK export
 * Converts markdown content to formatted PDF
 */
export function generateDskReadmePdf(
  images: DskImage[],
  dskFilename: string
): Blob {
  const doc = new jsPDF()
  let yPosition = 20

  // Title
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text(dskFilename, 20, yPosition)
  yPosition += 10

  // Generation date
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })
  doc.text(`Generated by Pixsaur on ${date}`, 20, yPosition)
  yPosition += 15

  // Contents section
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('Contents', 20, yPosition)
  yPosition += 8

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(
    `This DSK contains ${images.length} image(s) converted for Amstrad CPC.`,
    20,
    yPosition
  )
  yPosition += 10

  // Files table
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Files', 20, yPosition)
  yPosition += 5

  const filesTableData = images.map((image, index) => {
    const filename = `IMG${String(index + 1).padStart(5, '0')}.SCR`
    const hardware = image.cpcHardware === 'plus' ? 'CPC Plus' : 'CPC Classic'
    const mode = `Mode ${image.mode}`
    const dimensions = `${image.width}×${image.height}`
    const colors = String(image.nColors)
    return [filename, hardware, mode, dimensions, colors]
  })

  autoTable(doc, {
    startY: yPosition,
    head: [['Filename', 'Hardware', 'Mode', 'Dimensions', 'Colors']],
    body: filesTableData,
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185] },
    styles: { fontSize: 9 }
  })

  yPosition = (doc as any).lastAutoTable.finalY + 10

  // How to use section
  if (yPosition > 250) {
    doc.addPage()
    yPosition = 20
  }

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('How to use', 20, yPosition)
  yPosition += 8

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('From BASIC:', 20, yPosition)
  yPosition += 6

  doc.setFont('courier', 'normal')
  doc.setFontSize(9)
  doc.text('MEMORY &7FFF', 25, yPosition)
  yPosition += 5
  doc.text('LOAD"LOADER.BIN",&8000', 25, yPosition)
  yPosition += 5
  doc.text('A$="IMG00001.SCR"', 25, yPosition)
  yPosition += 5
  doc.text('CALL &8000, @A$', 25, yPosition)
  yPosition += 8

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  const loaderText =
    'The loader automatically detects CPC Classic or CPC Plus format and applies the appropriate palette.'
  const splitText = doc.splitTextToSize(loaderText, 170)
  doc.text(splitText, 20, yPosition)
  yPosition += 6 * splitText.length + 10

  // SCR File Format section
  if (yPosition > 230) {
    doc.addPage()
    yPosition = 20
  }

  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('SCR File Format', 20, yPosition)
  yPosition += 8

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(
    'Each .SCR file is 16KB (16384 bytes) with embedded metadata in the first 2KB block:',
    20,
    yPosition
  )
  yPosition += 10

  // Memory Layout table
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Memory Layout', 20, yPosition)
  yPosition += 5

  autoTable(doc, {
    startY: yPosition,
    head: [['Offset', 'Size', 'Description']],
    body: [
      ['0x0000-0x3FFF', '16384', 'Screen data (pixel data in CPC format)']
    ],
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185] },
    styles: { fontSize: 9 }
  })

  yPosition = (doc as any).lastAutoTable.finalY + 10

  // CPC Classic Format
  if (yPosition > 200) {
    doc.addPage()
    yPosition = 20
  }

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('CPC Classic Format (Metadata Area)', 20, yPosition)
  yPosition += 5

  autoTable(doc, {
    startY: yPosition,
    head: [['Offset', 'Size', 'Description']],
    body: [
      ['2000', '1', 'Border color (firmware index)'],
      ['2001-2016', '16', 'Palette colors (firmware indices)'],
      ['2017', '1', 'Border color (hardware value)'],
      ['2018-2033', '16', 'Palette colors (hardware values)'],
      ['2034', '1', 'Graphics mode (0, 1, or 2)'],
      ['2035', '1', 'Hardware type (0 = Classic)'],
      ['2036-2047', '12', 'Reserved/unused']
    ],
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185] },
    styles: { fontSize: 8 }
  })

  yPosition = (doc as any).lastAutoTable.finalY + 10

  // CPC Plus Format
  if (yPosition > 200) {
    doc.addPage()
    yPosition = 20
  }

  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('CPC Plus Format (Metadata Area)', 20, yPosition)
  yPosition += 5

  autoTable(doc, {
    startY: yPosition,
    head: [['Offset', 'Size', 'Description']],
    body: [
      ['2000-2001', '2', 'Border color (16-bit little-endian, GRB format)'],
      [
        '2002-2033',
        '32',
        '16 palette colors (16×2 bytes, little-endian, GRB format)'
      ],
      ['2034', '1', 'Graphics mode (0, 1, or 2)'],
      ['2035', '1', 'Hardware type (1 = Plus)'],
      ['2036-2047', '12', 'Reserved/unused']
    ],
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185] },
    styles: { fontSize: 8 }
  })

  yPosition = (doc as any).lastAutoTable.finalY + 8

  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.text('Note:', 20, yPosition)
  doc.setFont('helvetica', 'normal')
  yPosition += 5
  doc.text(
    'CPC Plus colors use 4 bits per component in GRB order:',
    20,
    yPosition
  )
  yPosition += 5
  doc.setFont('courier', 'normal')
  doc.text(
    'Format: 0000 GGGG RRRR BBBB (12-bit color from 4096 colors)',
    25,
    yPosition
  )
  yPosition += 5
  doc.setFont('helvetica', 'normal')
  doc.text('Stored as 16-bit little-endian values', 25, yPosition)
  yPosition += 10

  // Palette Information
  if (yPosition > 230) {
    doc.addPage()
    yPosition = 20
  }

  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Palette Information', 20, yPosition)
  yPosition += 8

  for (const [index, image] of images.entries()) {
    if (yPosition > 250) {
      doc.addPage()
      yPosition = 20
    }

    const filename = `IMG${String(index + 1).padStart(5, '0')}.SCR`
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text(
      `${filename} (${image.cpcHardware === 'plus' ? 'CPC Plus' : 'CPC Classic'})`,
      20,
      yPosition
    )
    yPosition += 6

    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')

    if (
      image.cpcHardware === 'classic' &&
      image.paletteFirmware &&
      image.paletteFirmware.length > 0
    ) {
      doc.text('Firmware indices:', 20, yPosition)
      yPosition += 5
      doc.setFont('courier', 'normal')
      const paletteText = `[${image.paletteFirmware.join(', ')}]`
      const splitPalette = doc.splitTextToSize(paletteText, 170)
      doc.text(splitPalette, 25, yPosition)
      yPosition += 5 * splitPalette.length + 5
    } else if (
      image.cpcHardware === 'plus' &&
      image.palettePlus &&
      image.palettePlus.length > 0
    ) {
      doc.text('Hardware values (GRB format):', 20, yPosition)
      yPosition += 5
      doc.setFont('courier', 'normal')
      const paletteText = `[${image.palettePlus
        .map((v) => `0x${v.toString(16).toUpperCase().padStart(3, '0')}`)
        .join(', ')}]`
      const splitPalette = doc.splitTextToSize(paletteText, 170)
      doc.text(splitPalette, 25, yPosition)
      yPosition += 5 * splitPalette.length + 8
    }

    doc.setFont('helvetica', 'normal')
  }

  // Footer
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setFont('helvetica', 'italic')
    doc.text(
      'Generated with Pixsaur (https://pixsaur.iiivan.org/) - Image converter for Amstrad CPC',
      20,
      285
    )
    doc.setFont('helvetica', 'normal')
    doc.text(`Page ${i} of ${totalPages}`, 180, 285)
  }

  return doc.output('blob')
}
