import type { DskImage } from '@/app/store/dsk-workspace/dsk-workspace'

/**
 * Generate README.md content for the DSK export
 */
export function generateDskReadme(
  images: DskImage[],
  dskFilename: string
): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  })

  let readme = `# ${dskFilename}\n\n`
  readme += `Generated by Pixsaur on ${date}\n\n`
  readme += `## Contents\n\n`
  readme += `This DSK contains ${images.length} image(s) converted for Amstrad CPC.\n\n`

  readme += `### Files\n\n`
  readme += `| Filename | Mode | Dimensions | Colors |\n`
  readme += `|----------|------|------------|--------|\n`

  for (const [index, image] of images.entries()) {
    const filename = `IMG${String(index + 1).padStart(5, '0')}.SCR`
    const mode = `Mode ${image.mode}`
    const dimensions = `${image.width}×${image.height}`
    const colors = image.nColors

    readme += `| ${filename} | ${mode} | ${dimensions} | ${colors} |\n`
  }

  readme += `\n### How to use\n\n`
  readme += ` From BASIC: \n`
  readme += `\`\`\`\n`
  readme += `LOAD"LOADER.BIN",&4000\n`
  readme += `A$="IMG00001.SCR" \n`
  readme += `CALL &4000, @A$\n`
  readme += `\`\`\`\n`
  readme += `Each .SCR file is self-contained with palette data\n\n`

  readme += `### Palette Information\n\n`
  for (const [index, image] of images.entries()) {
    readme += `**IMG${String(index + 1).padStart(5, '0')}.SCR**\n`
    if (image.paletteFirmware && image.paletteFirmware.length > 0) {
      readme += '```\n'
      readme += `[${image.paletteFirmware.join(', ')}]\n`
      readme += '```\n\n'
    }
  }

  readme += `---\n\n`
  readme += `Generated with [Pixsaur](https://pixsaur.iiivan.org/) - Image converter for Amstrad CPC\n`

  return readme
}
