name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      # Checkout code

      - name: Checkout code
        run: |
          git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY .
          git checkout $GITHUB_SHA

      # Install pnpm
      - name: Install pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.11.0 --activate

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Run tests
      - name: Run tests
        run: pnpm test
